### ISSUE TITLE
Breaking change in IntervalArithmetic 0.13

### ISSUE THREAD

**Issue by dpsanders** [MatthewStuber/EAGO.jl#20]
The latest tagged release of IntervalArithmetic 0.13 introduces a breaking change which seems to be affecting EAGO, according to http://juliarun-ci.s3.amazonaws.com/606e2260ef91c5dcbefdece629d6e2e4417c72a5/IntervalArithmetic_reverse_dependency_tests.html

I'm guessing that this is as a result of changing the semantics of things like `0.1 + x`:
previously, `0.1` was treated as the interval `@interval(0.1)`; now it is treated as the floating-point number 0.1 for efficiency.

You can add `@interval 0.1 + x` to recover the old behaviour.

(But note that using `@interval` performs some slow conversions.)

**Comment by dpsanders** [comment]
I sent a PR to upper bound the current tagged version of EAGO: https://github.com/JuliaLang/METADATA.jl/pull/14266

**Comment by MatthewStuber** [comment]
Thanks. This should be fixed in the latest EAGO release v0.1.1.
